# Generated by Django 5.2.8 on 2026-01-22 21:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
